routes/create.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from db.index import get_database

# special Python variable that represents the name of the current module. 
# in this case, it refers to the module where the blueprint is defined.
create_blueprint = Blueprint('create', __name__)

@create_blueprint.route('/')

def renderHTML():
    return render_template('create.html')

# decorator used to associate the createTask function with the specified route
# handles form submissions via a POST request
@create_blueprint.route('/', methods=['POST'])
def createTask():
    try:
        # get the database
        db = get_database()

        # access the "List" collection
        collection = db['List']

        # to access form data (data transmitted in a POST or PUT request) you can use the form attribute
        title = request.form['title']
        description = request.form['description']
        priority = request.form['priority']
        due_date = request.form['dueDate']

        # create a document (data) to be inserted
        task = {
            'title': title,
            'description': description,
            'priority': priority,
            'due_date': due_date,
            'completed': False
        }

        # insert the document into the collection
        collection.insert_one(task)

        # Set a flash message to inform the user about the successful task creation
        message = 'Task created successfully!'

        # Redirect the user back to the form page with the flash message
        # url_for function is a Flask helper function that generates URLs dynamically 
        # by using the name of the view function or endpoint rather than hardcoding the URL path
        flash(message)
        return redirect(url_for('create.renderHTML'))

    except Exception as error:
        flash('An error occured')
        print(error)
        return redirect(url_for('create.renderHTML'))

routes/search.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
from db.index import get_database
from bson import json_util, ObjectId
# was having attempted relative import beyond top-level package

search_blueprint = Blueprint('search', __name__)

@search_blueprint.route('/')

def renderHTML():
    return render_template('search.html')


@search_blueprint.route('/', methods=['POST'])

def findTask():
    try:
        # get the database
        db = get_database()

        # access the "List" collection
        collection = db['List']

        title = request.form['title']

        if title == '':
            tasks = list(collection.find({}))
            render_template('search_results.html')
        else:
            tasks = list(collection.find({'title': title}))

        if tasks:
            # in Flask's render_template function, any keyword arguments provided after
            # the template name are considered variables that can be accessed within the template
            return render_template('search_results.html', tasks=tasks)
        else:
            flash('No tasks found')
            return redirect(url_for('search.renderHTML'))
        

    except Exception as error:
        print(error)

@search_blueprint.route('/task/<task_id>', methods=['POST'])
def updateTask(task_id):
    try:
        # get the database
        db = get_database()

        # access the "List" collection
        collection = db['List']

        completed = request.form.get('completed')

        collection.update_one({'_id': ObjectId(task_id)}, 
                              {'$set': {'completed': bool(completed)}})

        flash('Task updated successfully!')
        
        return redirect(url_for('search.renderHTML'))

    except Exception as error:
        flash('An error occured')
        print(error)
        return redirect(url_for('search.renderHTML'))

templates/create.html
<!DOCTYPE html>
<html>
<head>
  <title>Create Task</title>
</head>
<body>
  <h1>Create Task</h1>
    <!-- An HTML form is used to collect user input -->
    <!-- action specifies where to send the form-data when a form is submitted -->
  <form id="createTask" action="/create" method="POST">
    <label for="title">Title:</label>
    <input type="text" id="title" name="title" required>

    <label for="description">Description:</label>
    <textarea id="description" name="description" required></textarea>

    <label for="priority">Priority:</label>
    <select id="priority" name="priority" required>
      <option value="low">Low</option>
      <option value="medium">Medium</option>
      <option value="high">High</option>
    </select>

    <label for="dueDate">Due Date:</label>
    <input type="date" id="dueDate" name="dueDate" required>

    <button type="submit">Create Task</button>
  </form>

  <!-- Jinja template is simply a text file -->
  <!-- Jinja can generate any text-based format -->
  <!-- the with statement makes it possible to create a new inner scope -->
  <!-- variables set within this scope are not visible outside of the scope -->
  {% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class="flash-messages">
      {% for message in messages %}
        <li>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
  {% endwith %}

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<head>
  <title>Create Task</title>
</head>
<body>
  <h1>Create Task</h1>
    <!-- An HTML form is used to collect user input -->
    <!-- action specifies where to send the form-data when a form is submitted -->
  <form id="task" action="/create" method="POST">
    <label for="title">Title:</label>
    <input type="text" id="title" name="title" required>

    <label for="description">Description:</label>
    <textarea id="description" name="description" required></textarea>

    <label for="priority">Priority:</label>
    <select id="priority" name="priority" required>
      <option value="low">Low</option>
      <option value="medium">Medium</option>
      <option value="high">High</option>
    </select>

    <label for="dueDate">Due Date:</label>
    <input type="date" id="dueDate" name="dueDate" required>

    <button type="submit">Create Task</button>
  </form>

  <!-- Jinja template is simply a text file -->
  <!-- Jinja can generate any text-based format -->
  <!-- the with statement makes it possible to create a new inner scope -->
  <!-- variables set within this scope are not visible outside of the scope -->
  {% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class="flash-messages">
      {% for message in messages %}
        <li>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

</body>
</html>

templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Task</title>
</head>
<body>
    <h1>Search Task</h1>
    <form id="searchTask" action="/search" method="POST">
        <label for="title">Enter Task To Search</label>
        <input type="text" id="title" name="title">
        <button type="submit">Search</button>
    </form>
    <p>To return all tasks simply hit the search button</p>
    
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <ul class="flash-messages">
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    {% endwith %}
</body>
</html>

templates/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Results</title>
</head>
<body>
    <h1>Search Results</h1>
        {% for task in tasks %}
        <form action="{{ url_for('search.updateTask', task_id=task._id) }}" method="POST">
            <p><strong>Title:</strong>{{ task.title }}</p>
            <p><strong>Description:</strong> {{ task.description }}</p>
            <p><strong>Due Date:</strong>{{ task.due_date }}</p>
            <p><strong>Status:</strong> {{ task.completed }}</p>
            <label for="completed">Mark as Complete:</label>
            <input type="checkbox" id="completed" name="completed" {% if task.completed %}checked{% endif %}>
            <button type="submit">Update Task</button>
        </form>
        {% endfor %}
</body>
</html>